//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Languages.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A conta(Agência/Número) {0}/{1} não foram encontradas para registrar a transação.
        /// </summary>
        public static string ContaInexistente {
            get {
                return ResourceManager.GetString("ContaInexistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta informada é inválida para atualizar os dados.
        /// </summary>
        public static string ContaInvalidaParaAtualizarDados {
            get {
                return ResourceManager.GetString("ContaInvalidaParaAtualizarDados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta inválida para gerar o hash da transação.
        /// </summary>
        public static string ErroGerarHashContaInvalida {
            get {
                return ResourceManager.GetString("ErroGerarHashContaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foi encontrado um lançamento já para esse identificador único {0}.
        /// </summary>
        public static string LancamentoDuplicado {
            get {
                return ResourceManager.GetString("LancamentoDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo do arquivo {0} é inválido para importação!.
        /// </summary>
        public static string TipoArquivoInvalido {
            get {
                return ResourceManager.GetString("TipoArquivoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token informado para decodificar é inválido!.
        /// </summary>
        public static string TokenInvalido {
            get {
                return ResourceManager.GetString("TokenInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Token informado para criação é inválido.
        /// </summary>
        public static string TokenInvalidoParaCriacao {
            get {
                return ResourceManager.GetString("TokenInvalidoParaCriacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi encontrado nenhuma transação para ser registrada.
        /// </summary>
        public static string TransacaoInvalida {
            get {
                return ResourceManager.GetString("TransacaoInvalida", resourceCulture);
            }
        }
    }
}
